# Generated by Django 4.1.4 on 2022-12-16 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Altai Territory', 'Altai Territory'), ('Amur Region', 'Amur Region'), ('Arkhangelsk Region', 'Arkhangelsk Region'), ('Astrakhan Region', 'Astrakhan Region'), ('Belgorod Region', 'Belgorod Region'), ('Bryansk Region', 'Bryansk Region'), ('Chechen Republic', 'Chechen Republic'), ('Chelyabinsk Region', 'Chelyabinsk Region'), ('Chukotka Autonomous Area', 'Chukotka Autonomous Area'), ('Chuvash Republic', 'Chuvash Republic'), ('City of\xa0Sevastopol', 'City of\xa0Sevastopol'), ('City of\xa0St Petersburg', 'City of\xa0St Petersburg'), ('Donetsk Republic', 'Donetsk Republic'), ('Irkutsk Region', 'Irkutsk Region'), ('Ivanovo Region', 'Ivanovo Region'), ('Jewish Autonomous Region', 'Jewish Autonomous Region'), ('Kabardino-Balkarian Republic', 'Kabardino-Balkarian Republic'), ('Kaliningrad Region', 'Kaliningrad Region'), ('Kaluga Region', 'Kaluga Region'), ('Kamchatka Territory', 'Kamchatka Territory'), ('Karachayevo-Circassian Republic', 'Karachayevo-Circassian Republic'), ('Kemerovo Region\xa0— Kuzbass', 'Kemerovo Region\xa0— Kuzbass'), ('Khabarovsk Territory', 'Khabarovsk Territory'), ('Khanty-Mansi Autonomous Area\xa0– Yugra', 'Khanty-Mansi Autonomous Area\xa0– Yugra'), ('Kherson Region', 'Kherson Region'), ('Kirov Region', 'Kirov Region'), ('Komi Republic', 'Komi Republic'), ('Kostroma Region', 'Kostroma Region'), ('Krasnodar Territory', 'Krasnodar Territory'), ('Krasnoyarsk Territory', 'Krasnoyarsk Territory'), ('Kurgan Region', 'Kurgan Region'), ('Kursk Region', 'Kursk Region'), ('Leningrad Region', 'Leningrad Region'), ('Lipetsk Region', 'Lipetsk Region'), ('Lugansk Republic', 'Lugansk Republic'), ('Magadan Region', 'Magadan Region'), ('Moscow', 'Moscow'), ('Moscow Region', 'Moscow Region'), ('Murmansk Region', 'Murmansk Region'), ('Nenets Autonomous Area', 'Nenets Autonomous Area'), ('Nizhny Novgorod Region', 'Nizhny Novgorod Region'), ('Novgorod Region', 'Novgorod Region'), ('Novosibirsk Region', 'Novosibirsk Region'), ('Omsk Region', 'Omsk Region'), ('Orel Region', 'Orel Region'), ('Orenburg Region', 'Orenburg Region'), ('Penza Region', 'Penza Region'), ('Perm Territory', 'Perm Territory'), ('Primorye Territory', 'Primorye Territory'), ('Pskov Region', 'Pskov Region'), ('Republic of\xa0Adygea', 'Republic of\xa0Adygea'), ('Republic of\xa0Altai', 'Republic of\xa0Altai'), ('Republic of\xa0Bashkortostan', 'Republic of\xa0Bashkortostan'), ('Republic of\xa0Buryatia', 'Republic of\xa0Buryatia'), ('Republic of\xa0Crimea', 'Republic of\xa0Crimea'), ('Republic of\xa0Dagestan', 'Republic of\xa0Dagestan'), ('Republic of\xa0Ingushetia', 'Republic of\xa0Ingushetia'), ('Republic of\xa0Kalmykia', 'Republic of\xa0Kalmykia'), ('Republic of\xa0Karelia', 'Republic of\xa0Karelia'), ('Republic of\xa0Khakassia', 'Republic of\xa0Khakassia'), ('Republic of\xa0Mari El', 'Republic of\xa0Mari El'), ('Republic of\xa0Mordovia', 'Republic of\xa0Mordovia'), ('Republic of\xa0North Ossetia-Alania', 'Republic of\xa0North Ossetia-Alania'), ('Republic of\xa0Sakha (Yakutia)', 'Republic of\xa0Sakha (Yakutia)'), ('Republic of\xa0Tatarstan', 'Republic of\xa0Tatarstan'), ('Republic of\xa0Tyva', 'Republic of\xa0Tyva'), ('Republic of\xa0Udmurtia', 'Republic of\xa0Udmurtia'), ('Rostov Region', 'Rostov Region'), ('Ryazan Region', 'Ryazan Region'), ('Sakhalin Region', 'Sakhalin Region'), ('Samara Region', 'Samara Region'), ('Saratov Region', 'Saratov Region'), ('Smolensk Region', 'Smolensk Region'), ('Stavropol Territory', 'Stavropol Territory'), ('Sverdlovsk Region', 'Sverdlovsk Region'), ('Tambov Region', 'Tambov Region'), ('Tomsk Region', 'Tomsk Region'), ('Trans-Baikal Territory', 'Trans-Baikal Territory'), ('Tula Region', 'Tula Region'), ('Tver Region', 'Tver Region'), ('Tyumen Region', 'Tyumen Region'), ('Ulyanovsk Region', 'Ulyanovsk Region'), ('Vladimir Region', 'Vladimir Region'), ('Volgograd Region', 'Volgograd Region'), ('Vologda Region', 'Vologda Region'), ('Voronezh Region', 'Voronezh Region'), ('Yamal-Nenets Autonomous Area', 'Yamal-Nenets Autonomous Area'), ('Yaroslavl Region', 'Yaroslavl Region'), ('Zaporozhye Region', 'Zaporozhye Region')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
