# Generated by Django 4.1.4 on 2022-12-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_payment_sberpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pazorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
